chat_terminal:
  prompt: "prompts/chat-terminal.txt"
  user: "User"
  agent: "Alice"

tc_local_llama: &tc_local_llama
  endpoint: "local-llama"
  configs:
    server_url: "http://127.0.0.1:40080"
    params:
      temperature: 0.75
      top_k: 40
      top_p: 0.9
      n_predict: 4096
      stop:
        - "[INST]"
        - "[User]:"

tc_openai: &tc_openai
  endpoint: "openai"
  configs:
    model: "gpt-3.5-turbo"
    credentials: "credentials/openai.yaml"
    params:
      stop:
        - "[User]:"

text_completion: *tc_local_llama
